version: '3.1'

services:
  wordpress:
    image: wordpress:cli
    container_name: wp-cli 
    restart: always
    depends_on:
      db:
        condition: service_healthy
    links:
      - db 
    ports:
      - 8080:8080
    environment:
      WORDPRESS_DB_HOST: ${DBH}
      WORDPRESS_DB_USER: ${DBU}
      WORDPRESS_DB_PASSWORD: ${DBP} 
      WORDPRESS_DB_NAME: ${DB}
      ADMIN_USER: ${WPU}
      ADMIN_PASS: ${WPP}
      ADMIN_EMAIL: ${WPE}
      WP_URL: ${WPURL}
      WP_TITLE: ${WPT}
    volumes:
      - ./wp-content:/opt/wp-content:z
      - ./scripts:/opt/scripts:ro
    command: bash -c "
      /opt/scripts/wp_container_start.sh"
  db:
    image: mysql:5.7
    container_name: wp-db 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DBRP}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DBU}
      MYSQL_PASSWORD: ${DBP}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
    ports:
      - 3306:3306 
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
      interval: 1s
      timeout: 1s
      retries: 60
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp-db-admin
    restart: always
    environment:
      PMA_HOST: "${DBH}"
      PMA_USER: "${DBU}"
      PMA_PASSWORD: "${DBP}"
      PMA_ARBITRARY: "1"
    ports:
      - 9999:80
